version: '3.7'

services:
  app:
    container_name: node_app
    build:
      context: .
      target: dev
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env

  grpc-test:
    image: gusaul/grpcox:latest
    env_file: .env
    ports:
      - ${TEST_GRPC_PORT}:${TEST_GRPC_PORT}
